project:
  type: website

website:
  title: "Grace Sidberry Does Stuff"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Research Shenanigans

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

